const checks=[
['Battery','Starts promptly; no clicking, sluggish cranking or noticeably dim headlights.'],
['Driving & charging','Give it a proper drive—not only a few minutes of idling.'],
['Tyre pressures','Check cold; inflate to the driver-door placard.'],
['Tyre condition','Inspect tread, cracks, bulges, objects and uneven wear.'],
['Spare tyre / repair kit','Check pressure and condition, or the repair-kit expiry.'],
['Engine oil','On level ground, engine off and settled; keep between dipstick marks.'],
['Coolant','Check reservoir only when cold. Never open a hot radiator cap.'],
['Brake fluid','Confirm between MIN and MAX; low fluid needs investigation.'],
['Lights & wipers','Test exterior lights, washers and wiper condition.']];
const key='yaris-care-v1';let state=JSON.parse(localStorage.getItem(key)||'null')||{done:[],odo:285915,services:[]};
if(!state.refuel)state.refuel={date:'',litres:'',price:'',unitPrice:'',fuelType:'U91',location:''};
state.refuel.fuelType=state.refuel.fuelType||'U91';state.refuel.unitPrice=state.refuel.unitPrice||'';
let nearbyCache=[];
const $=s=>document.querySelector(s),save=()=>localStorage.setItem(key,JSON.stringify(state));
function render(){
 $('#checklist').innerHTML=checks.map((c,i)=>`<label class="check ${state.done.includes(i)?'done':''}"><input type="checkbox" data-i="${i}" ${state.done.includes(i)?'checked':''}><div><strong>${c[0]}</strong><p>${c[1]}</p></div></label>`).join('');
 const n=state.done.length,p=Math.round(n/checks.length*100);$('#score').textContent=p+'%';$('#count').textContent=`${n} / ${checks.length}`;$('#ring').style.background=`conic-gradient(var(--gold) ${p}%,rgba(255,255,255,.14) 0)`;$('#odo').textContent=state.odo.toLocaleString();$('#fuel').textContent=state.refuel.date?new Date(state.refuel.date+'T00:00:00').toLocaleDateString('en-AU',{day:'numeric',month:'short'}):'—';
 const r=state.refuel,unit=r.unitPrice||((r.litres&&r.price)?(Number(r.price)/Number(r.litres)).toFixed(3):'');
 $('#fuelDetails').innerHTML=`<div class="fuel-field"><span>Date</span><strong>${r.date?new Date(r.date+'T00:00:00').toLocaleDateString('en-AU'):'Not recorded'}</strong></div><div class="fuel-field"><span>Fuel type</span><strong>${r.fuelType||'Not recorded'}</strong></div><div class="fuel-field"><span>Litres</span><strong>${r.litres?r.litres+' L':'Not recorded'}</strong></div><div class="fuel-field"><span>Price paid</span><strong>${r.price?'$'+Number(r.price).toFixed(2):'Not recorded'}</strong></div><div class="fuel-field"><span>Price per litre</span><strong>${unit?'$'+Number(unit).toFixed(3)+'/L':'Not recorded'}</strong></div><div class="fuel-field location"><span>Location</span><strong>${r.location||'Not recorded'}</strong></div>`;
 $('#services').innerHTML=state.services.length?state.services.map(x=>`<div class="record"><div><strong>${x.job}</strong><p>${x.date} · ${Number(x.km).toLocaleString()} km</p></div></div>`).join(''):'<div class="record"><div><strong>No records yet</strong><p>Add your latest service to begin your history.</p></div></div>';
 document.querySelectorAll('.check input').forEach(x=>x.onchange=()=>{let i=+x.dataset.i;state.done=x.checked?[...new Set([...state.done,i])]:state.done.filter(v=>v!==i);save();render()});
}
function modal(title,body,onSave){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').showModal();$('#modalSave').onclick=e=>{e.preventDefault();if(onSave()){$('#modal').close();save();render()}}}
document.querySelector('[data-action="odometer"]').onclick=()=>modal('Update odometer','<input id="mOdo" type="number" inputmode="numeric" value="'+state.odo+'" placeholder="Kilometres">',()=>{state.odo=+$('#mOdo').value;return !!state.odo});
function normaliseFuelRate(value){const rate=Number(value);return rate>10?rate/100:rate}
function calculateLitres(){const paid=Number($('#mPrice')?.value),rate=normaliseFuelRate($('#mUnitPrice')?.value),out=$('#litresResult');if(!out)return;out.textContent=paid>0&&rate>0?`Calculated litres: ${(paid/rate).toFixed(2)} L`:'Enter total paid and price per litre';}
function showStationSuggestions(term=''){const box=$('#stationSuggestions');if(!box)return;const q=term.trim().toLowerCase(),matches=nearbyCache.filter(s=>!q||s.name.toLowerCase().includes(q)).slice(0,6);box.innerHTML=matches.length?matches.map((s,i)=>`<button type="button" class="station-option" data-station="${i}"><strong>${s.name}</strong><small>${s.km.toFixed(1)} km away</small></button>`).join(''):'<button type="button" class="station-option">No matching nearby stations yet</button>';box.querySelectorAll('[data-station]').forEach((button,i)=>button.onclick=()=>{$('#mLocation').value=matches[i].name;box.innerHTML='';});}
function loadStationsForForm(){if(nearbyCache.length){showStationSuggestions();return}const box=$('#stationSuggestions');box.innerHTML='<button type="button" class="station-option">Finding stations near you…</button>';getNearbyStations().then(stations=>{nearbyCache=stations;showStationSuggestions($('#mLocation').value)}).catch(()=>box.innerHTML='<button type="button" class="station-option">Location unavailable—type the station manually</button>')}
function editRefuel(){let r=state.refuel;const fuelTypes=['U91','E10','U95','U98','Diesel','LPG'];modal('Log your last refuel',`<label class="field-label">Date<input id="mFuelDate" type="date" value="${r.date}"></label><span class="field-label">Fuel type</span><div class="fuel-types">${fuelTypes.map(type=>`<label class="fuel-type"><input type="radio" name="fuelType" value="${type}" ${r.fuelType===type?'checked':''}><span>${type}</span></label>`).join('')}</div><label class="field-label">Petrol station<input id="mLocation" autocomplete="off" value="${r.location}" placeholder="Start typing a station name"></label><div id="stationSuggestions" class="station-suggestions"></div><label class="field-label">Total price paid ($)<input id="mPrice" type="number" inputmode="decimal" step="0.01" value="${r.price}" placeholder="e.g. 62.50"></label><label class="field-label">Station price per litre ($/L or ¢/L)<input id="mUnitPrice" type="number" inputmode="decimal" step="0.001" value="${r.unitPrice}" placeholder="e.g. 1.899 or 189.9"></label><div id="litresResult" class="calculated-litres"></div>`,()=>{const paid=Number($('#mPrice').value),rate=normaliseFuelRate($('#mUnitPrice').value);if(!(paid>0&&rate>0)){alert('Enter the total paid and the station price per litre.');return false}state.refuel={date:$('#mFuelDate').value,fuelType:document.querySelector('input[name="fuelType"]:checked')?.value||'U91',price:paid.toFixed(2),unitPrice:rate.toFixed(3),litres:(paid/rate).toFixed(2),location:$('#mLocation').value.trim()};return true});$('#mPrice').oninput=calculateLitres;$('#mUnitPrice').oninput=calculateLitres;$('#mLocation').oninput=e=>showStationSuggestions(e.target.value);$('#mLocation').onfocus=()=>showStationSuggestions($('#mLocation').value);calculateLitres();loadStationsForForm();}
document.querySelector('[data-action="fuel"]').onclick=editRefuel;$('#editFuel').onclick=editRefuel;
document.querySelector('[data-action="note"]').onclick=()=>modal('Add reminder','<textarea id="mNote" placeholder="What should you remember?"></textarea>',()=>{let v=$('#mNote').value.trim();if(v)state.services.unshift({job:'Reminder: '+v,date:new Date().toLocaleDateString('en-AU'),km:state.odo});return !!v});
$('#addService').onclick=()=>modal('Add service record','<input id="mJob" placeholder="Service or repair"><input id="mDate" type="date"><input id="mKm" type="number" inputmode="numeric" value="'+state.odo+'">',()=>{if(!$('#mJob').value)return false;state.services.unshift({job:$('#mJob').value,date:$('#mDate').value||new Date().toLocaleDateString('en-AU'),km:$('#mKm').value});return true});
$('#resetMonth').onclick=()=>{if(confirm('Clear this month’s ticks?')){state.done=[];save();render()}};
$('#tripCheck').onclick=()=>alert('Before leaving: check tyre pressure and condition, oil, cold coolant level, lights, fuel, spare/repair kit and roadside assistance details.');
function distanceKm(a,b,c,d){const q=Math.PI/180,x=(c-a)*q,y=(d-b)*q;const z=Math.sin(x/2)**2+Math.cos(a*q)*Math.cos(c*q)*Math.sin(y/2)**2;return 12742*Math.asin(Math.sqrt(z))}
function getNearbyStations(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('Location unsupported'));navigator.geolocation.getCurrentPosition(async pos=>{let {latitude:lat,longitude:lon}=pos.coords;try{let query=`[out:json];nwr[amenity=fuel](around:7000,${lat},${lon});out center 20;`;let res=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',body:query});let data=await res.json();resolve(data.elements.map(s=>({name:s.tags?.name||s.tags?.brand||'Fuel station',lat:s.lat||s.center?.lat,lon:s.lon||s.center?.lon})).filter(s=>s.lat).map(s=>({...s,km:distanceKm(lat,lon,s.lat,s.lon)})).sort((a,b)=>a.km-b.km))}catch(e){reject(e)}},reject,{enableHighAccuracy:false,timeout:10000})})}
$('#findFuel').onclick=()=>{const status=$('#nearbyStatus'),box=$('#nearbyStations');if(!navigator.geolocation){status.textContent='Location is not supported on this device.';return}status.textContent='Finding nearby stations…';box.innerHTML='';navigator.geolocation.getCurrentPosition(async pos=>{let {latitude:lat,longitude:lon}=pos.coords;try{let query=`[out:json];nwr[amenity=fuel](around:7000,${lat},${lon});out center 15;`;let res=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',body:query});let data=await res.json();let stations=data.elements.map(s=>({name:s.tags?.name||s.tags?.brand||'Fuel station',lat:s.lat||s.center?.lat,lon:s.lon||s.center?.lon})).filter(s=>s.lat).map(s=>({...s,km:distanceKm(lat,lon,s.lat,s.lon)})).sort((a,b)=>a.km-b.km).slice(0,5);status.textContent=stations.length?'Nearest stations—compare their live U91 prices below.':'No nearby stations found.';box.innerHTML=stations.map(s=>`<div class="station"><span><strong>${s.name}</strong> · ${s.km.toFixed(1)} km</span><a target="_blank" rel="noopener" href="https://maps.apple.com/?daddr=${s.lat},${s.lon}&dirflg=d">Directions</a></div>`).join('')}catch(e){status.textContent='Nearby search is unavailable. Open Servo Saver below to search.'}},()=>status.textContent='Location access was not allowed. You can still use Servo Saver below.',{enableHighAccuracy:false,timeout:10000})};
$('#navChecks').onclick=()=>$('#checklist').scrollIntoView({behavior:'smooth'});$('#navRecords').onclick=()=>$('#services').scrollIntoView({behavior:'smooth'});render();
