const checks=[
['Battery','Starts promptly; no clicking, sluggish cranking or noticeably dim headlights.'],
['Driving & charging','Give it a proper drive—not only a few minutes of idling.'],
['Tyre pressures','Check cold; inflate to the driver-door placard.'],
['Tyre condition','Inspect tread, cracks, bulges, objects and uneven wear.'],
['Spare tyre / repair kit','Check pressure and condition, or the repair-kit expiry.'],
['Engine oil','On level ground, engine off and settled; keep between dipstick marks.'],
['Coolant','Check reservoir only when cold. Never open a hot radiator cap.'],
['Brake fluid','Confirm between MIN and MAX; low fluid needs investigation.'],
['Lights & wipers','Test exterior lights, washers and wiper condition.']];
const tripItems=[
['Tyres','Check cold pressure, tread, cracks, bulges and visible damage.'],
['Engine oil','Check on level ground with the engine off and settled.'],
['Water levels','When the engine is cold, check coolant; also check windscreen washer fluid. Never open a hot radiator cap.'],
['Lights','Test headlights, brake lights, indicators and hazard lights.'],
['Fuel','Confirm there is enough fuel for the planned trip.'],
['Spare / repair kit','Check the spare tyre or repair kit, jack and wheel tools.'],
['Roadside essentials','Carry roadside-assistance details, phone charger and emergency contacts.']];
const ODO_BASELINE=285915,ODO_MAX_DISTANCE=10000;
const key='yaris-care-v1';let state=JSON.parse(localStorage.getItem(key)||'null')||{done:[],odo:285915,services:[]};
if(!state.refuel)state.refuel={date:'',litres:'',price:'',unitPrice:'',fuelType:'U91',location:''};
state.refuel.fuelType=state.refuel.fuelType||'U91';state.refuel.unitPrice=state.refuel.unitPrice||'';
state.tripDone=state.tripDone||[];
let nearbyCache=[];
const $=s=>document.querySelector(s),save=()=>localStorage.setItem(key,JSON.stringify(state));
function render(){
 $('#checklist').innerHTML=checks.map((c,i)=>`<label class="check ${state.done.includes(i)?'done':''}"><input type="checkbox" data-i="${i}" ${state.done.includes(i)?'checked':''}><div><strong>${c[0]}</strong><p>${c[1]}</p></div></label>`).join('');
 const n=state.done.length;$('#count').textContent=`${n} / ${checks.length}`;$('#odo').textContent=state.odo.toLocaleString();$('#fuel').textContent=state.refuel.date?new Date(state.refuel.date+'T00:00:00').toLocaleDateString('en-AU',{weekday:'short',day:'numeric',month:'short'}):'—';
 const r=state.refuel,unit=r.unitPrice||((r.litres&&r.price)?(Number(r.price)/Number(r.litres)).toFixed(3):'');
 $('#fuelDetails').innerHTML=`<div class="fuel-field"><span>Date</span><strong>${r.date?new Date(r.date+'T00:00:00').toLocaleDateString('en-AU',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'}):'Not recorded'}</strong></div><div class="fuel-field"><span>Fuel type</span><strong>${r.fuelType||'Not recorded'}</strong></div><div class="fuel-field"><span>Litres</span><strong>${r.litres?r.litres+' L':'Not recorded'}</strong></div><div class="fuel-field"><span>Price paid</span><strong>${r.price?'$'+Number(r.price).toFixed(2):'Not recorded'}</strong></div><div class="fuel-field"><span>Price per litre</span><strong>${unit?'$'+Number(unit).toFixed(3)+'/L':'Not recorded'}</strong></div><div class="fuel-field location"><span>Location</span><strong>${r.location||'Not recorded'}</strong></div>`;
 $('#services').innerHTML=state.services.length?state.services.map(x=>`<div class="record"><div><strong>${x.job}</strong><p>${x.date} · ${Number(x.km).toLocaleString()} km</p></div></div>`).join(''):'<div class="record"><div><strong>No records yet</strong><p>Add your latest service to begin your history.</p></div></div>';
 document.querySelectorAll('.check input').forEach(x=>x.onchange=()=>{let i=+x.dataset.i;state.done=x.checked?[...new Set([...state.done,i])]:state.done.filter(v=>v!==i);save();render()});
}
function modal(title,body,onSave){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').showModal();$('#modalSave').onclick=e=>{e.preventDefault();if(onSave()){$('#modal').close();save();render()}}}
function updateOdoProgress(){const current=Number($('#mOdo')?.value)||ODO_BASELINE,difference=Math.max(0,current-ODO_BASELINE),percent=Math.min(100,difference/ODO_MAX_DISTANCE*100),bar=$('.odo-bar');$('#odoBarFill').style.width=percent+'%';bar.setAttribute('aria-valuenow',Math.min(difference,ODO_MAX_DISTANCE));$('#odoDifference').textContent=`${difference.toLocaleString()} km travelled`;$('#odoRemaining').textContent=difference>=ODO_MAX_DISTANCE?'10,000 km reached':`${(ODO_MAX_DISTANCE-difference).toLocaleString()} km remaining`}
document.querySelector('[data-action="odometer"]').onclick=()=>{modal('Odometer tracker',`<div class="odo-readings"><div><span>Baseline</span><strong>${ODO_BASELINE.toLocaleString()} km</strong><small>Fixed</small></div><label><span>Current</span><input id="mOdo" type="number" inputmode="numeric" min="${ODO_BASELINE}" value="${state.odo}" aria-label="Current odometer reading"></label></div><div class="odo-progress"><div class="odo-progress-head"><strong id="odoDifference"></strong><span id="odoRemaining"></span></div><div class="odo-bar" role="progressbar" aria-valuemin="0" aria-valuemax="10000"><div id="odoBarFill"></div></div><div class="odo-scale"><span>0 km</span><span>10,000 km</span></div></div>`,()=>{const current=Number($('#mOdo').value);if(!current||current<ODO_BASELINE){alert('Current odometer cannot be lower than the fixed baseline of 285,915 km.');return false}state.odo=current;return true});$('#mOdo').oninput=updateOdoProgress;updateOdoProgress()};
function normaliseFuelRate(value){const rate=Number(value);return rate>10?rate/100:rate}
function calculateLitres(){const paid=Number($('#mPrice')?.value),rate=normaliseFuelRate($('#mUnitPrice')?.value),out=$('#litresResult');if(!out)return;out.textContent=paid>0&&rate>0?`Calculated litres: ${(paid/rate).toFixed(2)} L`:'Enter total paid and price per litre';}
function showStationSuggestions(term=''){const box=$('#stationSuggestions');if(!box)return;const q=term.trim().toLowerCase(),matches=nearbyCache.filter(s=>!q||s.name.toLowerCase().includes(q)).slice(0,6);box.innerHTML=matches.length?matches.map((s,i)=>`<button type="button" class="station-option" data-station="${i}"><strong>${s.name}</strong><small>${s.km.toFixed(1)} km away</small></button>`).join(''):'<button type="button" class="station-option">No matching nearby stations yet</button>';box.querySelectorAll('[data-station]').forEach((button,i)=>button.onclick=()=>{$('#mLocation').value=matches[i].name;box.innerHTML='';});}
function loadStationsForForm(){if(nearbyCache.length){showStationSuggestions();return}const box=$('#stationSuggestions');box.innerHTML='<button type="button" class="station-option">Finding stations near you…</button>';getNearbyStations().then(stations=>{nearbyCache=stations;showStationSuggestions($('#mLocation').value)}).catch(()=>box.innerHTML='<button type="button" class="station-option">Location unavailable—type the station manually</button>')}
function editRefuel(){let r=state.refuel;const fuelTypes=['U91','E10','U95','U98','Diesel','LPG'];modal('Log your last refuel',`<label class="field-label">Date<input id="mFuelDate" type="date" value="${r.date}"></label><span class="field-label">Fuel type</span><div class="fuel-types">${fuelTypes.map(type=>`<label class="fuel-type"><input type="radio" name="fuelType" value="${type}" ${r.fuelType===type?'checked':''}><span>${type}</span></label>`).join('')}</div><label class="field-label">Petrol station<input id="mLocation" autocomplete="off" value="${r.location}" placeholder="Start typing a station name"></label><div id="stationSuggestions" class="station-suggestions"></div><label class="field-label">Total price paid ($)<input id="mPrice" type="number" inputmode="decimal" step="0.01" value="${r.price}" placeholder="e.g. 62.50"></label><label class="field-label">Station price per litre ($/L or ¢/L)<input id="mUnitPrice" type="number" inputmode="decimal" step="0.001" value="${r.unitPrice}" placeholder="e.g. 1.899 or 189.9"></label><div id="litresResult" class="calculated-litres"></div>`,()=>{const paid=Number($('#mPrice').value),rate=normaliseFuelRate($('#mUnitPrice').value);if(!(paid>0&&rate>0)){alert('Enter the total paid and the station price per litre.');return false}state.refuel={date:$('#mFuelDate').value,fuelType:document.querySelector('input[name="fuelType"]:checked')?.value||'U91',price:paid.toFixed(2),unitPrice:rate.toFixed(3),litres:(paid/rate).toFixed(2),location:$('#mLocation').value.trim()};return true});$('#mPrice').oninput=calculateLitres;$('#mUnitPrice').oninput=calculateLitres;$('#mLocation').oninput=e=>showStationSuggestions(e.target.value);$('#mLocation').onfocus=()=>showStationSuggestions($('#mLocation').value);calculateLitres();loadStationsForForm();}
document.querySelector('[data-action="fuel"]').onclick=editRefuel;$('#editFuel').onclick=editRefuel;
document.querySelector('[data-action="note"]').onclick=()=>modal('Add reminder','<textarea id="mNote" placeholder="What should you remember?"></textarea>',()=>{let v=$('#mNote').value.trim();if(v)state.services.unshift({job:'Reminder: '+v,date:new Date().toLocaleDateString('en-AU'),km:state.odo});return !!v});
$('#addService').onclick=()=>modal('Add service record','<input id="mJob" placeholder="Service or repair"><input id="mDate" type="date"><input id="mKm" type="number" inputmode="numeric" value="'+state.odo+'">',()=>{if(!$('#mJob').value)return false;state.services.unshift({job:$('#mJob').value,date:$('#mDate').value||new Date().toLocaleDateString('en-AU'),km:$('#mKm').value});return true});
function tripCollapsed(){return `<p class="eyebrow">BEFORE A LONG DRIVE</p><h2>Five-minute safety check</h2><p>Tyres, oil, water levels, lights, fuel and your roadside kit.</p><button id="tripCheck">Open checklist →</button>`}
function bindTripOpen(){$('#tripCheck').onclick=openTripChecklist}
function openTripChecklist(){const body=$('#tripBody');body.innerHTML=`<p class="eyebrow">BEFORE A LONG DRIVE</p><h2>Five-minute safety check</h2><div class="trip-list">${tripItems.map((item,i)=>`<label class="trip-check"><input type="checkbox" data-trip="${i}" ${state.tripDone.includes(i)?'checked':''}><span><strong>${item[0]}</strong><small>${item[1]}</small></span></label>`).join('')}</div><div class="trip-actions"><button id="clearTrip">Clear ticks</button><button id="closeTrip">Done ✓</button></div>`;body.querySelectorAll('[data-trip]').forEach(input=>input.onchange=()=>{const i=Number(input.dataset.trip);state.tripDone=input.checked?[...new Set([...state.tripDone,i])]:state.tripDone.filter(x=>x!==i);save()});$('#clearTrip').onclick=()=>{state.tripDone=[];save();openTripChecklist()};$('#closeTrip').onclick=()=>{body.innerHTML=tripCollapsed();bindTripOpen()}}
bindTripOpen();
function distanceKm(a,b,c,d){const q=Math.PI/180,x=(c-a)*q,y=(d-b)*q;const z=Math.sin(x/2)**2+Math.cos(a*q)*Math.cos(c*q)*Math.sin(y/2)**2;return 12742*Math.asin(Math.sqrt(z))}
function getNearbyStations(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('Location unsupported'));navigator.geolocation.getCurrentPosition(async pos=>{let {latitude:lat,longitude:lon}=pos.coords;try{let query=`[out:json];nwr[amenity=fuel](around:7000,${lat},${lon});out center 20;`;let res=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',body:query});let data=await res.json();resolve(data.elements.map(s=>({name:s.tags?.name||s.tags?.brand||'Fuel station',lat:s.lat||s.center?.lat,lon:s.lon||s.center?.lon})).filter(s=>s.lat).map(s=>({...s,km:distanceKm(lat,lon,s.lat,s.lon)})).sort((a,b)=>a.km-b.km))}catch(e){reject(e)}},reject,{enableHighAccuracy:false,timeout:10000})})}
function activateNav(button){document.querySelectorAll('nav button').forEach(item=>item.classList.toggle('active',item===button))}
$('#navHome').onclick=()=>{window.scrollTo({top:0,behavior:'smooth'});activateNav($('#navHome'))};
$('#navChecks').onclick=()=>{$('#checksSection').scrollIntoView({behavior:'smooth',block:'start'});activateNav($('#navChecks'))};
$('#navRecords').onclick=()=>{$('#services').scrollIntoView({behavior:'smooth',block:'start'});activateNav($('#navRecords'))};render();
