const checks=[
['Battery','Starts promptly; no clicking, sluggish cranking or noticeably dim headlights.'],
['Driving & charging','Give it a proper drive—not only a few minutes of idling.'],
['Tyre pressures','Check cold; inflate to the driver-door placard.'],
['Tyre condition','Inspect tread, cracks, bulges, objects and uneven wear.'],
['Spare tyre / repair kit','Check pressure and condition, or the repair-kit expiry.'],
['Engine oil','On level ground, engine off and settled; keep between dipstick marks.'],
['Coolant','Check reservoir only when cold. Never open a hot radiator cap.'],
['Brake fluid','Confirm between MIN and MAX; low fluid needs investigation.'],
['Lights & wipers','Test exterior lights, washers and wiper condition.']];
const tripItems=[
['Engine oil','Check on level ground with the engine off and settled.'],
['Fuel','Confirm there is enough fuel for the planned trip.'],
['Lights','Test headlights, brake lights, indicators and hazard lights.'],
['P plate sign','Confirm P plates are securely displayed and clearly visible at the front and rear.'],
['Roadside essentials','Caross jump start kit, power bank, car water, shopping bag, emergency contact informed, and car insurance validity.'],
['Spare / repair kit','Check the spare tyre or repair kit, jack and wheel tools.'],
['Tyres','Check cold pressure, tread, cracks, bulges and visible damage.'],
['Water levels','When the engine is cold, check coolant; also check windscreen washer fluid. Never open a hot radiator cap.']];
const ODO_BASELINE=285915,ODO_MAX_DISTANCE=10000,FUEL_MONTH_MAX=300;
const key='yaris-care-v1';let state=JSON.parse(localStorage.getItem(key)||'null')||{done:[],odo:285915,services:[]};
if(!state.refuel)state.refuel={date:'',litres:'',price:'',fuelType:'U91',location:''};
state.refuel.fuelType=state.refuel.fuelType||'U91';
if(!state.refuels){state.refuels=[];if(state.refuel.date&&Number(state.refuel.price)>0)state.refuels.push({...state.refuel});}
state.refuels.sort((a,b)=>String(b.date).localeCompare(String(a.date)));state.refuel=state.refuels[0]||state.refuel;
state.tripDone=state.tripDone||[];
if(state.tripChecklistVersion!==2){state.tripDone=[];state.tripChecklistVersion=2;}
if(!state.carNotes){state.carNotes=[];if(state.carInfo?.insurance)state.carNotes.push({title:'Car insurance information',body:state.carInfo.insurance});if(state.carInfo?.parts)state.carNotes.push({title:'Parts replaced',body:state.carInfo.parts+(state.carInfo.date?'\nDate: '+state.carInfo.date:'')});}
const $=s=>document.querySelector(s),save=()=>localStorage.setItem(key,JSON.stringify(state)),escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function todayInputValue(){const date=new Date();return`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
function formatDate(value){if(!value)return'';let date,match=String(value).match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(/^\d{4}-\d{2}-\d{2}$/.test(value))date=new Date(value+'T00:00:00');else if(match)date=new Date(Number(match[3]),Number(match[2])-1,Number(match[1]));else date=new Date(value);if(Number.isNaN(date.getTime()))return String(value);const day=String(date.getDate()).padStart(2,'0'),month=date.toLocaleDateString('en-AU',{month:'short'}),weekday=date.toLocaleDateString('en-AU',{weekday:'short'});return`${weekday} / ${day} ${month}`;}
function fuelMonthSeries(count=6){const now=new Date();return Array.from({length:count},(_,index)=>{const date=new Date(now.getFullYear(),now.getMonth()-(count-1-index),1),key=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`,total=state.refuels.filter(item=>String(item.date).slice(0,7)===key).reduce((sum,item)=>sum+(Number(item.price)||0),0);return{key,label:date.toLocaleDateString('en-AU',{month:'short'}),fullLabel:date.toLocaleDateString('en-AU',{month:'long',year:'numeric'}),total};});}
function render(){
 $('#checklist').innerHTML=checks.map((c,i)=>`<label class="check ${state.done.includes(i)?'done':''}"><input type="checkbox" data-i="${i}" ${state.done.includes(i)?'checked':''}><div><strong>${c[0]}</strong><p>${c[1]}</p></div></label>`).join('');
 const fuelMonths=fuelMonthSeries(),monthlyFuelCost=fuelMonths[fuelMonths.length-1].total;
 const n=state.done.length;$('#count').textContent=`${n} / ${checks.length}`;$('#odo').textContent=state.odo.toLocaleString();$('#fuel').textContent=`A$${monthlyFuelCost.toFixed(2)}`;
 const r=state.refuels[0]||state.refuel;
 $('#fuelDetails').innerHTML=`<div class="fuel-field"><span>Date</span><strong>${r.date?formatDate(r.date):'Not recorded'}</strong></div><div class="fuel-field"><span>Fuel type</span><strong>${r.fuelType||'Not recorded'}</strong></div><div class="fuel-field payment"><span>Fuel paid</span><strong>${r.price?'A$'+Number(r.price).toFixed(2):'Not recorded'}</strong></div>`;
 $('#fuelChart').setAttribute('aria-label',fuelMonths.map(month=>`${month.fullLabel}: A$${month.total.toFixed(2)}`).join('; '));
 $('#fuelChart').innerHTML=`<div class="fuel-chart-grid" aria-hidden="true"><span data-value="A$300"></span><span data-value="A$200"></span><span data-value="A$100"></span><span data-value="A$0"></span></div><div class="fuel-bars">${fuelMonths.map(month=>{const height=Math.min(100,month.total/FUEL_MONTH_MAX*100);return`<div class="fuel-bar-column" title="${month.fullLabel}: A$${month.total.toFixed(2)}"><strong>${month.total?`$${month.total.toFixed(0)}`:'—'}</strong><div class="fuel-bar-track"><span class="fuel-bar-fill" style="height:${height}%"></span></div><small>${month.label}</small></div>`}).join('')}</div>`;
 $('#services').innerHTML=state.services.length?state.services.map((x,index)=>{const isReminder=x.type==='reminder'||/^Reminder:\s*/.test(x.job),title=isReminder?x.job.replace(/^Reminder:\s*/,''):x.job,details=isReminder?formatDate(x.date):`${formatDate(x.date)} · ${Number(x.km).toLocaleString()} km`;return `<div class="record-swipe" data-service="${index}"><span class="swipe-action swipe-edit" aria-hidden="true">Edit</span><span class="swipe-action swipe-delete" aria-hidden="true">Delete</span><div class="record"><div><strong>${escapeHtml(title)}</strong><p>${escapeHtml(details)}</p></div></div></div>`}).join(''):'<div class="record"><div><strong>No reminders yet</strong><p>Add a reminder to begin your list.</p></div></div>';
 $('#undoReminder').disabled=!state.lastDeletedReminder;
 document.querySelectorAll('.check input').forEach(x=>x.onchange=()=>{let i=+x.dataset.i;state.done=x.checked?[...new Set([...state.done,i])]:state.done.filter(v=>v!==i);save();render()});
 bindReminderSwipes();
}
function fitDialogToViewport(){const dialog=$('#modal');if(!dialog.open)return;const viewport=window.visualViewport,width=viewport?.width||window.innerWidth,height=viewport?.height||window.innerHeight,offsetLeft=viewport?.offsetLeft||0,offsetTop=viewport?.offsetTop||0,safeTop=parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--safe-top'))||0,top=Math.max(offsetTop+8,safeTop+8),bottom=offsetTop+height;dialog.style.setProperty('--dialog-width',`${Math.max(0,Math.min(420,width-20))}px`);dialog.style.setProperty('--dialog-left',`${offsetLeft+width/2}px`);dialog.style.setProperty('--dialog-height',`${Math.max(0,bottom-top-8)}px`);dialog.style.setProperty('--dialog-top',`${top}px`)}
function modal(title,body,onSave){const dialog=$('#modal'),saveButton=$('#modalSave'),cancelButton=$('#modal .dialog-actions button[value="cancel"]');$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;saveButton.hidden=false;saveButton.textContent='Save';cancelButton.textContent='Cancel';dialog.showModal();fitDialogToViewport();requestAnimationFrame(fitDialogToViewport);saveButton.onclick=e=>{e.preventDefault();if(onSave()){dialog.close();save();render()}}}
window.visualViewport?.addEventListener('resize',fitDialogToViewport);
window.visualViewport?.addEventListener('scroll',fitDialogToViewport);
$('#modalBody').addEventListener('focusin',event=>{if(event.target.matches('input,textarea'))setTimeout(()=>event.target.scrollIntoView({block:'center',behavior:'smooth'}),120)});
function updateOdoProgress(){const current=Number($('#mOdo')?.value)||ODO_BASELINE,difference=Math.max(0,current-ODO_BASELINE),percent=Math.min(100,difference/ODO_MAX_DISTANCE*100),bar=$('.odo-bar');$('#odoBarFill').style.width=percent+'%';bar.setAttribute('aria-valuenow',Math.min(difference,ODO_MAX_DISTANCE));$('#odoDifference').textContent=`${difference.toLocaleString()} km travelled`;$('#odoRemaining').textContent=difference>=ODO_MAX_DISTANCE?'10,000 km reached':`${(ODO_MAX_DISTANCE-difference).toLocaleString()} km remaining`}
document.querySelector('[data-action="odometer"]').onclick=()=>{modal('Odometer tracker',`<div class="odo-readings"><div><span>Baseline</span><strong>${ODO_BASELINE.toLocaleString()} km</strong><small>Fixed</small></div><label><span>Current</span><input id="mOdo" type="number" inputmode="numeric" min="${ODO_BASELINE}" value="${state.odo}" aria-label="Current odometer reading"></label></div><div class="odo-progress"><div class="odo-progress-head"><strong id="odoDifference"></strong><span id="odoRemaining"></span></div><div class="odo-bar" role="progressbar" aria-valuemin="0" aria-valuemax="10000"><div id="odoBarFill"></div></div><div class="odo-scale"><span>0 km</span><span>10,000 km</span></div></div>`,()=>{const current=Number($('#mOdo').value);if(!current||current<ODO_BASELINE){alert('Current odometer cannot be lower than the fixed baseline of 285,915 km.');return false}state.odo=current;return true});$('#mOdo').oninput=updateOdoProgress;updateOdoProgress()};
function addFuelPayment(){modal('Latest payment','<label class="field-label">Fuel paid<input id="mPrice" type="number" inputmode="decimal" min="0.01" step="0.01" placeholder="e.g. 62.50" autofocus></label>',()=>{const paid=Number($('#mPrice').value);if(!(paid>0)){alert('Enter the amount paid for fuel.');return false}const savedRefuel={date:todayInputValue(),fuelType:'',price:paid.toFixed(2),litres:'',location:''};state.refuels.unshift(savedRefuel);state.refuels.sort((a,b)=>String(b.date).localeCompare(String(a.date)));state.refuel=state.refuels[0];return true});}
function editRefuel(){const hasLatest=state.refuels.length>0,r=hasLatest?{...state.refuels[0]}:{date:todayInputValue(),price:'',fuelType:''},fuelTypes=['U91','E10','U95','U98','Diesel','LPG'];modal(hasLatest?'Edit latest refuel':'Add fuel log',`<label class="field-label">Date<input id="mFuelDate" type="date" value="${r.date}"></label><label class="field-label">Fuel paid<input id="mPrice" type="number" inputmode="decimal" min="0.01" step="0.01" value="${r.price}" placeholder="e.g. 62.50"></label><span class="field-label">Fuel type</span><div class="fuel-types">${fuelTypes.map(type=>`<label class="fuel-type"><input type="radio" name="fuelType" value="${type}" ${r.fuelType===type?'checked':''}><span>${type}</span></label>`).join('')}</div>`,()=>{const date=$('#mFuelDate').value,paid=Number($('#mPrice').value),fuelType=document.querySelector('input[name="fuelType"]:checked')?.value||'';if(!date){alert('Choose the refuel date.');return false}if(!(paid>0)){alert('Enter the amount paid for fuel.');return false}const savedRefuel={date,fuelType,price:paid.toFixed(2),litres:'',location:''};if(hasLatest)state.refuels[0]=savedRefuel;else state.refuels.unshift(savedRefuel);state.refuels.sort((a,b)=>String(b.date).localeCompare(String(a.date)));state.refuel=state.refuels[0];return true});}
document.querySelector('[data-action="fuel"]').onclick=addFuelPayment;$('#editFuel').onclick=editRefuel;
document.querySelector('[data-action="note"]').onclick=()=>modal('Add reminder','<textarea id="mNote" placeholder="What should you remember?"></textarea>',()=>{let v=$('#mNote').value.trim();if(v)state.services.unshift({type:'reminder',job:v,date:new Date().toLocaleDateString('en-AU')});return !!v});
$('#addService').onclick=()=>modal('Add service record','<input id="mJob" placeholder="Service or repair"><input id="mDate" type="date"><input id="mKm" type="number" inputmode="numeric" value="'+state.odo+'">',()=>{if(!$('#mJob').value)return false;state.services.unshift({job:$('#mJob').value,date:$('#mDate').value||new Date().toLocaleDateString('en-AU'),km:$('#mKm').value});return true});
function editReminder(index){const item=state.services[index];if(!item)return;const isReminder=item.type==='reminder'||/^Reminder:\s*/.test(item.job),title=isReminder?item.job.replace(/^Reminder:\s*/,''):item.job;modal('Edit reminder',`<label class="field-label">Reminder<textarea id="mReminder" placeholder="What should you remember?">${escapeHtml(title)}</textarea></label>`,()=>{const value=$('#mReminder').value.trim();if(!value)return false;item.job=value;if(isReminder)item.type='reminder';return true});}
function undoLastReminder(){const deleted=state.lastDeletedReminder;if(!deleted)return;state.services.splice(Math.min(deleted.index,state.services.length),0,deleted.item);delete state.lastDeletedReminder;save();render()}
function bindReminderSwipes(){document.querySelectorAll('.record-swipe').forEach(row=>{const card=row.querySelector('.record'),index=Number(row.dataset.service);let startX=0,startY=0,distance=0,armed=false,timer=null;const reset=()=>{clearTimeout(timer);timer=null;armed=false;distance=0;row.classList.remove('swipe-armed','swiping-left','swiping-right');card.style.transform='';card.style.transition='transform .2s ease'};row.addEventListener('pointerdown',event=>{if(event.pointerType==='mouse'&&event.button!==0)return;row.setPointerCapture?.(event.pointerId);card.style.transition='none';startX=event.clientX;startY=event.clientY;distance=0;timer=setTimeout(()=>{armed=true;row.classList.add('swipe-armed');if(navigator.vibrate)navigator.vibrate(12)},320)});row.addEventListener('pointermove',event=>{const moveX=event.clientX-startX,moveY=event.clientY-startY;if(!armed){if(Math.abs(moveX)>10||Math.abs(moveY)>10)clearTimeout(timer);return}if(Math.abs(moveY)>Math.abs(moveX)+10){reset();return}event.preventDefault();distance=Math.max(-115,Math.min(115,moveX));card.style.transform=`translateX(${distance}px)`;row.classList.toggle('swiping-left',distance<0);row.classList.toggle('swiping-right',distance>0)});row.addEventListener('pointerup',()=>{clearTimeout(timer);if(!armed){reset();return}if(distance<=-70){card.style.transition='transform .18s ease';card.style.transform='translateX(-100%)';setTimeout(()=>{state.lastDeletedReminder={item:{...state.services[index]},index};state.services.splice(index,1);save();render()},180);return}if(distance>=70){reset();editReminder(index);return}reset()});row.addEventListener('pointercancel',reset);row.addEventListener('contextmenu',event=>{if(armed)event.preventDefault()})})}
async function downloadBackup(){const status=$('#backupStatus'),fileName=`yaris-care-backup-${todayInputValue()}.json`,contents=JSON.stringify({app:'My Yaris Care',backupVersion:1,exportedAt:new Date().toISOString(),data:state},null,2),file=new File([contents],fileName,{type:'application/json'});status.textContent='Preparing backup…';try{if(navigator.canShare?.({files:[file]})){await navigator.share({title:'My Yaris Care backup',text:'Save this backup in Files on your iPhone.',files:[file]});status.textContent='Backup ready in Files.';return}const url=URL.createObjectURL(file),link=document.createElement('a');link.href=url;link.download=fileName;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='Backup downloaded.'}catch(error){if(error.name==='AbortError'){status.textContent='Backup cancelled.';return}status.textContent='Could not open the backup. Please try again.'}}
function tripCollapsed(){return `<p class="eyebrow">BEFORE A LONG DRIVE</p><h2>Five-minute safety check</h2><p>Tyres, oil, water levels, lights, fuel and your roadside kit.</p><button id="tripCheck">Open checklist →</button>`}
function bindTripOpen(){$('#tripCheck').onclick=openTripChecklist}
function openTripChecklist(){const body=$('#tripBody');body.innerHTML=`<p class="eyebrow">BEFORE A LONG DRIVE</p><h2>Five-minute safety check</h2><div class="trip-list">${tripItems.map((item,i)=>`<label class="trip-check"><input type="checkbox" data-trip="${i}" ${state.tripDone.includes(i)?'checked':''}><span><strong>${item[0]}</strong><small>${item[1]}</small></span></label>`).join('')}</div><div class="trip-actions"><button id="clearTrip">Clear ticks</button><button id="closeTrip">Done ✓</button></div>`;body.querySelectorAll('[data-trip]').forEach(input=>input.onchange=()=>{const i=Number(input.dataset.trip);state.tripDone=input.checked?[...new Set([...state.tripDone,i])]:state.tripDone.filter(x=>x!==i);save()});$('#clearTrip').onclick=()=>{state.tripDone=[];save();openTripChecklist()};$('#closeTrip').onclick=()=>{body.innerHTML=tripCollapsed();bindTripOpen()}}
bindTripOpen();
function carNotesList(){const body=$('#modalBody'),saveButton=$('#modalSave'),cancelButton=$('#modal .dialog-actions button[value="cancel"]');$('#modalTitle').textContent='Car notes';saveButton.hidden=true;cancelButton.textContent='Close';body.innerHTML=`<div class="car-note-list">${state.carNotes.length?state.carNotes.map((note,i)=>`<button type="button" class="car-note-title" data-note="${i}">${escapeHtml(note.title)}</button>`).join(''):'<p class="empty-note">No car notes yet.</p>'}</div><button type="button" class="add-note-btn" id="addCarNote">＋ Add note</button>`;body.querySelectorAll('[data-note]').forEach(button=>button.onclick=()=>viewCarNote(Number(button.dataset.note)));$('#addCarNote').onclick=()=>editCarNote();}
function viewCarNote(index){const note=state.carNotes[index],body=$('#modalBody'),saveButton=$('#modalSave');$('#modalTitle').textContent=note.title;saveButton.hidden=true;body.innerHTML=`<div class="note-body">${escapeHtml(note.body)||'<span class="empty-note">No body text.</span>'}</div><div class="note-actions"><button type="button" id="backToNotes">← Titles</button><button type="button" id="editCarNote">Edit</button></div>`;$('#backToNotes').onclick=carNotesList;$('#editCarNote').onclick=()=>editCarNote(index);}
function editCarNote(index){const note=index===undefined?{title:'',body:''}:state.carNotes[index],body=$('#modalBody'),saveButton=$('#modalSave'),cancelButton=$('#modal .dialog-actions button[value="cancel"]');$('#modalTitle').textContent=index===undefined?'New car note':'Edit car note';cancelButton.textContent='Close';body.innerHTML=`<label class="field-label">Title<input id="mNoteTitle" value="${escapeHtml(note.title)}" placeholder="e.g. Car insurance"></label><label class="field-label">Body<textarea id="mNoteBody" placeholder="Write the note details here">${escapeHtml(note.body)}</textarea></label><button type="button" class="back-note-btn" id="backToNotes">← Back to titles</button>`;saveButton.hidden=false;saveButton.textContent='Save';$('#backToNotes').onclick=carNotesList;saveButton.onclick=e=>{e.preventDefault();const title=$('#mNoteTitle').value.trim();if(!title){alert('Add a title for this note.');return}const savedNote={title,body:$('#mNoteBody').value.trim()};if(index===undefined)state.carNotes.unshift(savedNote);else state.carNotes[index]=savedNote;save();carNotesList();};}
function openCarNotes(){modal('Car notes','',()=>true);carNotesList();}
function activateNav(button){document.querySelectorAll('nav button').forEach(item=>item.classList.toggle('active',item===button))}
$('#navHome').onclick=()=>{window.scrollTo({top:0,behavior:'smooth'});activateNav($('#navHome'))};
$('#navChecks').onclick=()=>{$('#checksSection').scrollIntoView({behavior:'smooth',block:'start'});activateNav($('#navChecks'))};
$('#navRecords').onclick=()=>{$('#services').scrollIntoView({behavior:'smooth',block:'start'});activateNav($('#navRecords'))};render();
$('#navCar').onclick=()=>{openCarNotes();activateNav($('#navCar'))};
$('#undoReminder').onclick=undoLastReminder;
$('#downloadBackup').onclick=downloadBackup;
